"use client";

import './globals.css';
import "bootstrap/dist/css/bootstrap.css";

import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Header from '@/app/components/Header/Header';
import Footer from '@/app/components/Footer/Footer';
import AuthContext from './context/AuthContext';


const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Loja TáNaMão',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={nunito.className}>
        <AuthContext>
          <Header/>
          {children}
          <Footer/>
        </AuthContext>
        </body>
    </html>
  )
}
